#!/usr/bin/env bash
# This script that displays Best School 10 times, but for the 9th iteration,
# displays Best School and then Hi on a new line

counter=1
while [ $counter -le 20 ]
do
    echo $counter
    case $counter in
	4)
	    echo "bad luck from China"
	    ;;

	9)
	    echo "bad luck from Japan"
	    ;;

	17)
	    echo "bad luck from Italy"
	    ;;
	*)
	    ;;
    esac
    ((counter++))
done
