#!/usr/bin/env bash
# This script gives information about the school file
check="school"
if [ -e "$check" ]
then
    echo "school file exists"

    if [ -s "$check" ]
    then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi

    if [ -f "$check" ]
    then
	echo "school is a regular file"
    fi

else
    echo "school file does not exist"
fi
