#!/usr/bin/env bash
# script that configures an Ubuntu server with the
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts hosts_temp
sed -i s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g hosts_temp
cp -f hosts_temp /etc/hosts
